version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers

jobs:
  clone_and_hash:
    <<: *defaults
    working_directory: ~/circle-monorepo-test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-project-metadata-{{ .Branch }}
            - v1-project-metadata-master

      - run:
          name: Initialize project metadata
          command: |
            mkdir -p .project-metadata
            touch .project-{kustomize,first,second}-hash
      - run:
          name: Hash projects
          command: |
            git log --pretty=format:'%H' -n 1 -- \
              kustomize \
              services/first/kustomize \
              services/second/kustomize > .project-kustomize-hash.new
            git log --pretty=format:'%H' -n 1 -- \
              yarn.lock \
              package.json \
              services/first > .project-first-hash.new
            git log --pretty=format:'%H' -n 1 -- \
              yarn.lock \
              package.json \
              services/second > .project-second-hash.new
      - run:
          name: Determine changed projects
          command: |
            if ! diff .project-kustomize-hash{,.new} > /dev/null; then
              touch .project-metadata/.project-kustomize-changed
            fi
            if ! diff .project-first-hash{,.new} > /dev/null; then
              touch .project-metadata/.project-first-changed
            fi
            if ! diff .project-second-hash{,.new} > /dev/null; then
              touch .project-metadata/.project-second-changed
            fi
      - run:
          name: Set current project hashes
          command: |
            mv .project-kustomize-hash{.new,}
            mv .project-first-hash{.new,}
            mv .project-second-hash{.new,}
      - persist_to_workspace:
          root: .
          paths:
            - .project-metadata

      - save_cache:
          key: v1-project-metadata-{{ .Branch }}-{{ epoch }}
          paths:
            - .project-kustomize-hash
            - .project-first-hash
            - .project-second-hash

  service_first:
    <<: *defaults
    working_directory: ~/circle-monorepo-test/services/first
    steps:
      - checkout: { path: ~/circle-monorepo-test }
      - attach_workspace: { at: . }
      - run:
          name: Project First - install dependencies
          command: |
            [ -e .project-metadata/.project-first-changed ] || exit 0
            yarn

      - run:
          name: Project First - Build
          command: |
            [ -e .project-metadata/.project-first-changed ] || exit 0
            yarn build

      - run:
          name: Project First - Test
          command: |
            [ -e .project-metadata/.project-first-changed ] || exit 0
            echo "run tests"

      - run:
          name: Project First - Build image
          command: |
            [ -e .project-metadata/.project-first-changed ] || exit 0
            echo "build image"

      - run:
          name: Project First - Push image
          command: |
            [ -e .project-metadata/.project-first-changed ] || exit 0
            echo "push image"

  service_second:
    <<: *defaults
    working_directory: ~/circle-monorepo-test/services/second
    steps:
      - checkout: { path: ~/circle-monorepo-test }
      - attach_workspace: { at: . }
      - run:
          name: Project Second - install dependencies
          command: |
            [ -e .project-metadata/.project-second-changed ] || exit 0
            yarn

      - run:
          name: Project Second - Build
          command: |
            [ -e .project-metadata/.project-second-changed ] || exit 0
            yarn build

      - run:
          name: Project Second - Test
          command: |
            [ -e .project-metadata/.project-second-changed ] || exit 0
            echo "run tests"

      - run:
          name: Project Second - Build image
          command: |
            [ -e .project-metadata/.project-second-changed ] || exit 0
            echo "build image"

      - run:
          name: Project Second - Push image
          command: |
            [ -e .project-metadata/.project-second-changed ] || exit 0
            echo "push image"

  deploy:
    <<: *defaults
    working_directory: ~/circle-monorepo-test
    steps:
      - checkout: { path: ~/circle-monorepo-test }
      - attach_workspace: { at: . }
      - run:
          name: Kustomize - build
          command: |
            [ -e .project-metadata/.project-kustomize-changed ] || exit 0
            echo "Kustomize build"

      - run:
          name: k8s - lint
          command: |
            [ -e .project-metadata/.project-kustomize-changed ] || exit 0
            echo "k8s lint"

      - run:
          name: k8s - deploy
          command: |
            [ -e .project-metadata/.project-kustomize-changed ] || exit 0
            [ "${CIRCLE_BRANCH}" == "master" ] || exit 0
            echo "Deploying to staging"
            echo "Deploying to production"

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - service_first:
          requires:
            - clone_and_hash
      - service_second:
          requires:
            - clone_and_hash
      - deploy:
          requires:
            - service_first
            - service_second
