---
apiVersion: v1
kind: Service
metadata:
  name: ignored
  labels:
    app: ignored
spec:
  type: ClusterIP
  selector:
    app: ignored
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
