---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second
  labels:
    app: second
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
        - name: second
          image: docker.io/hashicorp/http-echo:latest
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
