---
apiVersion: v1
kind: Service
metadata:
  name: second
  labels:
    app: second
spec:
  type: ClusterIP
  selector:
    app: second
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
