---
apiVersion: v1
kind: Service
metadata:
  name: first
  labels:
    app: first
spec:
  type: ClusterIP
  selector:
    app: first
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
