---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first
  labels:
    app: first
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first
  template:
    metadata:
      labels:
        app: first
    spec:
      containers:
        - name: first
          image: docker.io/hashicorp/http-echo:latest
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
